# SOPS configuration for app secrets
# Generate keys: run `just app init-secrets myapp` in the infra repo
#
# &app   — the server uses this key's private counterpart to decrypt at runtime
# &local — your local Age key so you can edit secrets with `sops`

keys:
  - &app REPLACE_WITH_APP_PUBLIC_KEY
  - &local REPLACE_WITH_LOCAL_PUBLIC_KEY

creation_rules:
  - path_regex: secrets/.*\.enc\.yaml$
    key_groups:
      - age:
          - *app
          - *local
